### ISSUE TITLE
Float quantities are parsed as int

### ISSUE THREAD

**Issue by aryan1113** [Prajwalrayal/SplitIt#1]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/87320561/202895825-1af4d2c8-f6ea-4b61-9457-fc3008290a3c.png">

**Comment by Prajwalrayal** [comment]
Oh! Thanks for pointing this out, can you fix this?

**Comment by aryan1113** [comment]
> Oh! Thanks for pointing this out, can you fix this?

Sorry for the late reply, I've fixed it now
Can you pls review the same ?
